### PR TITLE
 WithdrawMarket RPC: use BlindTransactionWithData in sendToMany

### LINKED ISSUE #409: WithdrawMarket RPC: failed to recover information about author of range proof
I am trying to withdraw from a funded market and I got this error `"2 UNKNOWN: failed to recover information about author of range proof"`

My `WithdrawMarket` request payload

```json
{
  "market": {
    "base_asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
    "quote_asset": "cba679e5ad472447cb26236c2a7d58198b334770ebcffefb5fbba9e6463e9b1e"
  },
  "balance_to_withdraw": {
    "base_amount": 100,
    "quote_amount": 100
  },
  "millisat_per_byte": 1000,
  "address": "el1qqtaa843j80v9tthju77ul7m385e429dafwqmcvsq9yqt7ucl0ku2fxzgtwwdsr2trwuuzuwukd9jvqxy5c4zcyzvht5y30ca6",
  "push": false
}
```

My `Balances`

```
{
  "balances": [
    {
      "balance": {
        "base_amount": "1000",
        "quote_amount": "100000000"
      },
      "fee": {
        "basis_point": "0",
        "fixed": {
          "base_fee": "650",
          "quote_fee": "1"
        }
      }
    }
  ]
}
```

My `ListMarket`

```
{
  "markets": [
    {
      "market": {
        "base_asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
        "quote_asset": "cba679e5ad472447cb26236c2a7d58198b334770ebcffefb5fbba9e6463e9b1e"
      },
      "fee": {
        "basis_point": "0",
        "fixed": {
          "base_fee": "650",
          "quote_fee": "1"
        }
      },
      "tradable": false,
      "account_index": "5",
      "price": {
        "base_price": 0.0008500000112690032,
        "quote_price": 1200
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by sekulicd**
This updates private method sendToMany so that it uses BlindTransactionWithData instead BlindTransactionWithKeys since stored unspents dont holds proofs info(tnx @altafan for the advise)
It fixes issue with Withdraw bug endpoint.

This closes #409 

@tiero @altafan please review.

### CODE REVIEW

File: internal/core/application/wallet_service.go [hunk 1]
```diff
@@ -381,6 +381,18 @@ func sendToMany(opts sendToManyOpts) (string, error) {
...
+	index := 0
+	for _, v := range updateResult.SelectedUnspents {
+		inputBlindingData[index] = wallet.BlindingData{
+			Asset:         v.Asset(),
+			Amount:        v.Value(),
+			AssetBlinder:  v.AssetBlinder(),
+			AmountBlinder: v.ValueBlinder(),
+		}
+		index++
+	}
```
Comment (altafan) [inline internal/core/application/wallet_service.go:394]:
```suggestion
	inputBlindingData := make(map[int]wallet.BlindingData, 0)
	for _, v := range updateResult.SelectedUnspents {
		inputBlindingData = append(inputBlindingData, wallet.BlindingData{
			Asset:         v.Asset(),
			Amount:        v.Value(),
			AssetBlinder:  v.AssetBlinder(),
			AmountBlinder: v.ValueBlinder(),
		})
	}
```

File: internal/core/application/wallet_service.go [hunk 2]
```diff
@@ -400,16 +412,28 @@ func sendToMany(opts sendToManyOpts) (string, error) {
...
 	}
 
+	for _, v := range feeUpdateResult.SelectedUnspents {
+		inputBlindingData[index] = wallet.BlindingData{
+			Asset:         v.Asset(),
+			Amount:        v.Value(),
+			AssetBlinder:  v.AssetBlinder(),
+			AmountBlinder: v.ValueBlinder(),
+		}
+	}
```
Comment (altafan) [inline internal/core/application/wallet_service.go:422]:
```suggestion
	for _, v := range feeUpdateResult.SelectedUnspents {
		inputBlindingData = append(inputBlindingData, wallet.BlindingData{
			Asset:         v.Asset(),
			Amount:        v.Value(),
			AssetBlinder:  v.AssetBlinder(),
			AmountBlinder: v.ValueBlinder(),
		})
	}
```

File: internal/core/application/wallet_service.go (hunk 1 above)
Comment (sekulicd) [reply internal/core/application/wallet_service.go:394]: @altafan how can we use append with map?

Comment (altafan) [reply internal/core/application/wallet_service.go:394]: sorry I misread it 🙏. Resolving.

File: internal/core/application/wallet_service.go [hunk 3]
```diff
@@ -400,16 +412,28 @@ func sendToMany(opts sendToManyOpts) (string, error) {
 		return "", err
 	}
 
+	for _, v := range feeUpdateResult.SelectedUnspents {
+		inputBlindingData[index] = wallet.BlindingData{
+			Asset:         v.Asset(),
+			Amount:        v.Value(),
+			AssetBlinder:  v.AssetBlinder(),
+			AmountBlinder: v.ValueBlinder(),
+		}
```
Comment (altafan) [inline internal/core/application/wallet_service.go:421]: forgot to increment `index`?

Comment (sekulicd) [reply internal/core/application/wallet_service.go:421]: no its in L393

**Review by tiero — APPROVED** [review]

File: internal/core/application/wallet_service.go (hunk 3 above)
Comment (altafan) [reply internal/core/application/wallet_service.go:421]: That's done when looping over `updateResult.SelectedUnspents`, here we're looping over `feeUpdateResult.SelectedUnspents`!

Comment (tiero) [reply internal/core/application/wallet_service.go:421]: cc @sekulicd

Comment (sekulicd) [reply internal/core/application/wallet_service.go:421]: i expected that feeUpdateResult could add only one more input for fee, if this is true that no need for increment.
@altafan can we have more than one input?

Comment (altafan) [reply internal/core/application/wallet_service.go:421]: Of course it is possible to use more than one unspents to pay for fees.. as this is done, it would give problems for sure in such cases. Please fix it.

Comment (sekulicd) [reply internal/core/application/wallet_service.go:421]: Done

**Review by altafan — APPROVED** [review]
