### PR TITLE
Check swap messages & minor fixes

### LINKED ISSUE #337: Panic after TradePropose
```
panic: runtime error: index out of range [6] with length 6

goroutine 24322 [running]:
github.com/tdex-network/tdex-daemon/pkg/wallet.(*Wallet).BlindSwapTransactionWithData(0xc011a91c20, 0xc011c99000, 0x4b64, 0xc011c765d0, 0xc055d7b950, 0x0, 0x2c, 0x0, 0x0, 0xc011bebdd0)
	/tdex-daemon/pkg/wallet/blind.go:373 +0x7fb
github.com/tdex-network/tdex-daemon/internal/core/application.fillProposal(0xc011b02c00, 0x18, 0x18, 0x1109e80, 0xc0109646c0, 0xc010f42a80, 0x33, 0x33, 0xc011b0b4a0, 0xf, ...)
	/tdex-daemon/internal/core/application/trade_service.go:648 +0xc05
github.com/tdex-network/tdex-daemon/internal/core/application.tradeManager.FillProposal(...)
	/tdex-daemon/internal/core/application/types.go:193
github.com/tdex-network/tdex-daemon/internal/core/application.(*tradeService).TradePropose(0xc0109f93e0, 0x1102de0, 0xc005d02690, 0xc01094b040, 0x40, 0xc01094b080, 0x40, 0x0, 0x1109e80, 0xc0109646c0, ...)
	/tdex-daemon/internal/core/application/trade_service.go:287 +0x775
github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/handler.traderHandler.tradePropose(0x11050e0, 0xc0109f93e0, 0xc0516c07c0, 0x1108f20, 0xc005ef8820, 0xe20501, 0xc005ef8820)
	/tdex-daemon/internal/interfaces/grpc/handler/trade.go:213 +0x1cd
github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/handler.traderHandler.TradePropose(...)
	/tdex-daemon/internal/interfaces/grpc/handler/trade.go:64
github.com/tdex-network/tdex-protobuf/generated/go/trade._Trade_TradePropose_Handler(0xe3e880, 0xc005daac40, 0x1106940, 0xc0000ca3c0, 0x1, 0xdf9be0)
	/go/pkg/mod/github.com/tdex-network/tdex-protobuf@v0.0.0-20210324125236-78f6c6c0618b/generated/go/trade/trade_grpc.pb.go:282 +0x10b
github.com/tdex-network/tdex-daemon/internal/interfaces/grpc/interceptor.streamLogger(0xe3e880, 0xc005daac40, 0x1106940, 0xc0000ca3c0, 0xc005e8ec80, 0x1025700, 0x1102de0, 0xc005d02690)
	/tdex-daemon/internal/interfaces/grpc/interceptor/logger.go:27 +0xbe
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0000c8700, 0x110a840, 0xc0107e9d40, 0xc010dbe800, 0xc010a39110, 0x1596880, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1448 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0000c8700, 0x110a840, 0xc0107e9d40, 0xc010dbe800, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1521 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc053dd6010, 0xc0000c8700, 0x110a840, 0xc0107e9d40, 0xc010dbe800)
	/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

```

### PR DESCRIPTION
**Pull request by altafan**
This reintroduces some checks into the pkg/swap methods: for `Request` and `Accept` messages we now check that the inputs and outputs of the partial transaction are _sane_ and that each one has a relative blind key, in case these are provided.
This prevents the daemon from panicking in case of bad requests made by clients.

Minor fixes:
* start observing tx only if trade is accepted in TradePropose()
* add a TransactionHandler interface to extract unspents from raw tx. This enables mocking this exact step in component tests.
* fix sleep time in trade service tests in order to prevent race conditions.

Closes #337.

Please @tiero, review this.

### CODE REVIEW

File: pkg/swap/request.go [hunk 1]
```diff
@@ -90,6 +90,7 @@ func checkTxAndBlindKeys(
 
 	checkOutputKeys := outBlindKeys != nil
 	for i, out := range ptx.UnsignedTx.Outputs {
+		fmt.Println(hex.EncodeToString(out.Script))
```
Comment (tiero) [inline pkg/swap/request.go:93]: remove

**Comment by tiero** [comment]
CI is failing
